import './my_companies/my_companies.js'
import './publish_vacancy/publish_vacancy.js'
import './my_vacancies/my_vacancies.js'
import './my_vacancies/edit/my_vacancies_edit.js'
import './vacancies/vacancies.js'
