import './personal/personal'
import './specialization/specialization'
import './specialization/specialization_test'
import './experiences/experiences'
import './contacts/contacts'
import './eductions/educations'